# Generated by Django 4.2.7 on 2025-12-05 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='类别名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='类别编码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.category', verbose_name='父类别')),
            ],
            options={
                'verbose_name': '类别',
                'verbose_name_plural': '类别',
                'db_table': 'categories',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='物品名称')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='物品编码')),
                ('barcode', models.CharField(blank=True, max_length=100, verbose_name='条形码')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('stock', models.IntegerField(default=0, verbose_name='库存数量')),
                ('min_stock', models.IntegerField(default=0, verbose_name='最低库存')),
                ('warehouse_location', models.CharField(blank=True, max_length=100, verbose_name='仓位')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/%Y/%m/', verbose_name='图片')),
                ('status', models.CharField(choices=[('normal', '正常'), ('low_stock', '低库存'), ('out_of_stock', '缺货'), ('discontinued', '停产')], default='normal', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.category', verbose_name='类别')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_items', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='suppliers.supplier', verbose_name='供应商')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='warehouses.warehouse', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '物品',
                'verbose_name_plural': '物品',
                'db_table': 'items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='items_code_47e090_idx'), models.Index(fields=['barcode'], name='items_barcode_07fc1d_idx'), models.Index(fields=['status'], name='items_status_bc9bcb_idx')],
            },
        ),
    ]
