# Generated by Django 4.2.7 on 2025-12-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['name'], name='items_name_dd4454_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category'], name='items_categor_a72b5f_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['warehouse'], name='items_warehou_dbed7a_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['created_at'], name='items_created_78d389_idx'),
        ),
    ]
