# Generated by Django 4.2.7 on 2025-12-05 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('in', '入库'), ('out', '出库'), ('transfer', '调拨'), ('adjust', '调整'), ('check', '盘点')], max_length=20, verbose_name='操作类型')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('before_stock', models.IntegerField(verbose_name='操作前库存')),
                ('after_stock', models.IntegerField(verbose_name='操作后库存')),
                ('recipient', models.CharField(blank=True, max_length=100, verbose_name='领用人')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='领用部门')),
                ('purpose', models.CharField(blank=True, max_length=200, verbose_name='用途')),
                ('from_warehouse', models.CharField(blank=True, max_length=100, verbose_name='源仓库')),
                ('to_warehouse', models.CharField(blank=True, max_length=100, verbose_name='目标仓库')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='inventory.item', verbose_name='物品')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '库存操作',
                'verbose_name_plural': '库存操作',
                'db_table': 'inventory_operations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['operation_type'], name='inventory_o_operati_08a043_idx'), models.Index(fields=['created_at'], name='inventory_o_created_498f0b_idx')],
            },
        ),
    ]
