# Generated by Django 4.2.7 on 2025-12-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventoryoperation',
            index=models.Index(fields=['item'], name='inventory_o_item_id_016c2c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryoperation',
            index=models.Index(fields=['operation_type', 'created_at'], name='inventory_o_operati_ee45d5_idx'),
        ),
    ]
