# Generated by Django 4.2.7 on 2025-12-10 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0002_inventoryoperation_inventory_o_item_id_016c2c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryoperation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='inventoryoperation',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_operations', to=settings.AUTH_USER_MODEL, verbose_name='删除人'),
        ),
        migrations.AddField(
            model_name='inventoryoperation',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否已删除'),
        ),
    ]
