# Generated by Django 4.2.7 on 2025-12-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='仓库名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='仓库编码')),
                ('location', models.CharField(max_length=500, verbose_name='位置')),
                ('capacity', models.IntegerField(verbose_name='容量')),
                ('manager', models.CharField(max_length=100, verbose_name='负责人')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '仓库',
                'verbose_name_plural': '仓库',
                'db_table': 'warehouses',
                'ordering': ['-created_at'],
            },
        ),
    ]
