# Generated by Django 4.2.7 on 2025-12-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='capacity',
            field=models.IntegerField(default=0, verbose_name='容量'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='仓库编码'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='location',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='位置'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='manager',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='联系电话'),
        ),
    ]
