# Generated by Django 4.2.7 on 2025-12-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_alter_warehouse_capacity_alter_warehouse_code_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['is_active'], name='warehouses_is_acti_178fdd_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['code'], name='warehouses_code_339055_idx'),
        ),
    ]
